FROM python:3.10

WORKDIR /app

COPY ./requirements.txt /app/requirements.txt

RUN pip install --no-cache-dir --upgrade -r /app/requirements.txt

ADD llm_colab.py /app/

ADD uebersetzte_datei.txt /app/

ENV PYTHONUNBUFFERED=1

CMD [ "python", "llm_colab.py" ]