"""users and roles tables

Revision ID: 36843f85f419
Revises: 
Create Date: 2019-05-04 19:34:46.664863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36843f85f419'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_role_role'), 'db_role', ['role'], unique=True)
    op.create_table('db_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['db_role.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_db_user_name'), 'db_user', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_db_user_name'), table_name='db_user')
    op.drop_table('db_user')
    op.drop_index(op.f('ix_db_role_role'), table_name='db_role')
    op.drop_table('db_role')
    # ### end Alembic commands ###
